name: Reusable CI

on:
  workflow_call:
    inputs:
      language:
        description: >
          Primary language / build system of the project: c-cpp, rust, go, python.
        required: true
        type: string
      run_tests:
        description: "Run tests in addition to build."
        required: false
        type: boolean
        default: true

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        if: inputs.language == 'rust'
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Go
        if: inputs.language == 'go'
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Set up Python
        if: inputs.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build (C/C++)
        if: inputs.language == 'c-cpp'
        run: |
          cmake -S . -B build
          cmake --build build --config Release

      - name: Test (C/C++)
        if: inputs.language == 'c-cpp' && inputs.run_tests == true
        run: |
          ctest --test-dir build --output-on-failure

      - name: Build (Rust)
        if: inputs.language == 'rust'
        run: |
          cargo build --locked --all-targets

      - name: Test (Rust)
        if: inputs.language == 'rust' && inputs.run_tests == true
        run: |
          cargo test --locked --all-targets

      - name: Build (Go)
        if: inputs.language == 'go'
        run: |
          go build ./...

      - name: Test (Go)
        if: inputs.language == 'go' && inputs.run_tests == true
        run: |
          go test ./...

      - name: Install dependencies (Python)
        if: inputs.language == 'python'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test (Python)
        if: inputs.language == 'python' && inputs.run_tests == true
        run: |
          if [ -f pyproject.toml ] || [ -d tests ]; then
            pytest
          else
            echo "No Python tests configured."
          fi
